import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Genshin Impact",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="Home">
        {children}
        <div className="bgImage">
          <Image src="/img/childe.jpg" alt="bg" fill></Image>
        </div>
      </body>
    </html>
  );
}
